config/routes.rb
Rails.application.routes.draw do
  mount ::Caffeinate::Engine => '/caffeinate'

  get 'cookies/index'
  devise_for :users

  resources :users do
    resources :consultations
    post 'consultations/new', to: 'consultations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#coming_soon'
  root to: 'pages#home'
  # get 'home', to: 'pages#home'
  # get 'families', to: 'pages#family_home'
  get 'educators', to: 'pages#educator_home'
  get 'webinar', to: 'pages#webinar'
  # TODO Update Courses and Change from Workshops
  get 'courses', to: 'workshops#workshops'
  get 'ambassador/family', to: 'pages#ambassador_family'
  get 'ambassador/educators', to: 'pages#ambassador_educator'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact_us'
  get 'consultations', to: 'pages#consultations'
  get 'consultations/purchase', to: 'pages#consultation_purchase'
  get 'GWM', to: 'pages#grow_with_me'
  get 'account', to: 'pages#account'

  get 'cookies', to: 'cookies#index'

  resources :bookmarks, only: [:index, :show, :destroy]
  post 'bookmarks', to: 'bookmarks#create'

  resources :workshops, only: [:show] do
    member do
      get :preview
    end
  end

  get 'workshops', to: 'workshops#workshops'
  post "workshops/add_to_cart/:id", to: "workshops#add_to_cart", as: "add_to_cart"
  post "workshops/add_to_cart_ws_page/:id", to: "workshops#add_to_cart_ws_page", as: "add_to_cart_ws_page"
  delete "workshops/remove_from_cart/:id", to: "workshops#remove_from_cart", as: "remove_from_cart"
  delete 'workshops/remove_from_cart_cart_page/:id', to:'workshops#remove_from_cart_cart_page', as: "remove_from_cart_cart_page"

  get 'create_shopping_cart_order', to: 'orders#create_shopping_cart_order'
  get 'create_consult_order', to: 'orders#create_consult_order'

  resources :orders, only: [:show, :create] do
      resources :payments, only: :new
  end

  get 'cart', to: 'cart#cart'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/workshop.rb
class Workshop < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :orders, through: :products
  validates :category, inclusion: { in: %w(families educators), message: "%{value} is not a valid category" }
  monetize :price_cents
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  skip_before_action :authenticate_user!, except: :preview

  def workshops
    # cart_params
    moodle = MoodleRb.new(ENV['MOODLE_WEBSERVICES_TOKEN'], ENV['MOODLE_URL'])
    moodle_workshops = moodle.courses.index

    moodle_workshops.each do |workshop|
      next if workshop['id'] == 1
      next if Workshop.find_by(moodle_id: workshop['id'])

      new_workshop = Workshop.new
      new_workshop.fullname = workshop['fullname']
      new_workshop.shortname = workshop['shortname']
      new_workshop.language = workshop['lang']
      new_workshop.moodle_id = workshop['id']

      summary_string = workshop['summary'].match(/>.+</).to_s
      new_workshop.summary = summary_string[1...-1]

      case workshop['categoryid']
      when 1
        new_workshop.category = 'families'
      when 2
        new_workshop.category = 'educators'
      else
        new_workshop.category = 'families'
      end

      new_workshop.save
    end
    @q = Workshop.ransack(cart_params[:q])
    @workshops = @q.result(distinct: true)
    if cart_params[:fav] == '1'
      @workshops = @workshops.joins(:bookmarks).where("user_id = #{current_user.id}")
    end
  end

  def show
    @workshop = Workshop.find(params[:id])
  end

  def add_to_cart
    id = cart_params[:id].to_i
    session[:ws_cart] << id unless session[:ws_cart].include?(id)
    redirect_to workshops_path(params: cart_params)
  end

  def remove_from_cart
    id = cart_params[:id].to_i
    session[:ws_cart].delete(id)
    redirect_to workshops_path(params: cart_params)
  end

  def add_to_cart_ws_page
    workshop = Workshop.find(params[:id])
    id = params[:id].to_i
    session[:ws_cart] << id unless session[:ws_cart].include?(id)
    redirect_to workshops_path(workshop)
  end

  def remove_from_cart_cart_page
    id = params[:id].to_i
    session[:ws_cart].delete(id)
    redirect_to cart_path
  end

  def preview
    @workshop = Workshop.find(params[:id])
    if !PreviewDripper.subscriptions.find_by(user_id: current_user.id).nil?
      PreviewDripper.subscribe(@workshop, user: current_user)
      PreviewDripper.perform!
    end
    flash.now[:notice] = "You are subscribed and have access to this preview."

  end

  private

  def cart_params
    params.permit(:id, :fav, q: {})
  end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/preview.html.erb
<section class="position-relative py-48" style="height: 90vh; background-image: linear-gradient(to bottom,rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.6)), url('https://images.unsplash.com/photo-1534224563519-fea04849cadf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80'); background-repeat: no-repeat; background-size: cover; background-position: center;">
  <div class="position-relative container h-100 text-center d-flex flex-column align-items-center justify-content-center">
    <h2 class="my-4 text-white"> I'm the Preview Page for <%= @workshop.shortname %></h2>
    <h6 class="my-4 text-white"><%= @workshop.summary %></h6>
    <div class="text-center">
          <a class="btn btn-primary" style="margin-top: 200px;" href="">Enrollment Coming Soon</a>
    </div>
  </div>
</section>

<%# Key Content (Hidden) %>
<%# <section class="overflow-hidden py-5 bg-light">
  <div class="container">
    <div class="row align-items-center mb-5 mb-lg-0">
      <div class="col-12 col-lg-5 mb-5 mb-lg-0">
        <h6 class="mb-5 lead lh-lg text-muted">Summary</h6>
        <p class="mb-5 lead lh-lg text-muted">A very clear and concise summary of the workshop</p>
        <div class="d-flex align-items-center mb-5">
          <svg class="me-4" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M14 40H40" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M8 40V34L34 8L40 14L14 40H8Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M34 20L28 14" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
          <div>
            <p class="mb-0">Key Content/Learning 1</p>
          </div>
        </div>
        <div class="d-flex align-items-center mb-5">
          <svg class="me-4" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M24 44C24 44 40 36 40 24V10L24 4L8 10V24C8 36 24 44 24 44Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M16 23L22 29L34 17" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
          <div>
            <p class="mb-0">Key Content/Learning 2</p>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <svg class="me-4" width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M24 30C27.866 30 31 26.866 31 23C31 19.134 27.866 16 24 16C20.134 16 17 19.134 17 23C17 26.866 20.134 30 24 30Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M42 23.9999C42.006 28.6858 40.1784 33.188 36.908 36.5439C35.2324 38.2726 33.2261 39.6466 31.0086 40.5839C28.791 41.5212 26.4075 42.0028 24 41.9999C21.5925 42.0028 19.209 41.5212 16.9914 40.5839C14.7739 39.6466 12.7676 38.2726 11.092 36.5439C9.03644 34.4289 7.53208 31.8412 6.71122 29.0084C5.89036 26.1756 5.77815 23.1845 6.38447 20.2982C6.99079 17.4119 8.29705 14.7188 10.1884 12.4557C12.0797 10.1927 14.4981 8.42902 17.2309 7.3199C19.9638 6.21079 22.9273 5.79018 25.8608 6.09507C28.7943 6.39996 31.608 7.42102 34.0543 9.06843C36.5006 10.7158 38.5047 12.9391 39.8902 15.5428C41.2757 18.1464 42.0002 21.0506 42 23.9999V23.9999Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
            <path d="M11.092 36.544C12.5768 34.5144 14.5197 32.8639 16.7627 31.7268C19.0056 30.5897 21.4853 29.9981 24 30C26.5148 29.9981 28.9945 30.5897 31.2374 31.7268C33.4804 32.8639 35.4233 34.5144 36.908 36.544" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
          <div>
            <p class="mb-0">Key Content/Learning 3</p>
          </div>
        </div>
      </div>
        <div class="col-lg-2"></div>
      <div data-controller="vidcontrol" class="position-relative col-12 col-lg-5" style="height: 28rem; background-image: url('https://images.unsplash.com/photo-1534224563519-fea04849cadf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80'); background-repeat: no-repeat; background-size: cover; background-position: center;">
        <a href= "javascript:;" data-action="click->vidcontrol#play" >
          <div data-vidcontrol-target="linkbtn" class="position-absolute top-0 start-0 w-100 h-100 bg-dark d-flex align-items-center justify-content-center " style="opacity: 75%;">
              <i class="fa-regular fa-circle-play text-white opacity-50" style="font-size: 100px;"></i>
          </div>
        </a>
        <div data-vidcontrol-target="video" style="padding:60.69% 0 0 0;position:relative; left: 50%; top: 50%; transform: translateX(-50%)translateY(-50%); display:none;">
          <iframe id="my-iframe" src="https://player.vimeo.com/video/740325291?h=b5efb52e53&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="New Recording - 8/17/2022, 1:08:13 PM"></iframe>
        </div>
        <script src="https://player.vimeo.com/api/player.js"></script>
      </div>
    </div>
  </div>
</section> %>

<%# Spacing (Hidden) %>
<%# <section class="spacer border-top border-primary">
</section> %>

<%# Curriculum (Hidden) %>
<%# <section class="py-5">
  <div class="container">
    <div class="row text-center">
      <h6 class="mb-5 lead lh-lg text-muted">Workshop Curriculum</h6>
    </div>
    <div class="row">
      <div class="col-lg-2"></div>
            <div class="accordion col-lg-8" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Item #1
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Item #2
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Item #3
            </button>
          </h2>
          <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</section> %>

<%# Enrollment (hidden) %>
<%# <section class="py-5 bg-primary">
  <div class="container">
    <div class="mw-4xl mx-auto text-center"> %>
      <%# <%= form_with url: orders_path do %>
        <%# <%= hidden_field_tag 'workshop_id', @workshop.id %>
        <%# <%= submit_tag "Enroll for #{humanized_money_with_symbol(@workshop.price)}", class: 'btn btn-secondary d-block d-md-inline-block my-3' %>
      <%# <% end %>
    <%# </div>
  </div>
</section> %>

app/views/workshops/workshops.html.erb
<div class="container">
  <div class="row d-flex justify-content-between">
    <%# <div class="dropdown col-md-3 col-xs-12 my-1" data-controller="dropdownover">
      <button class="btn btn-secondary dropdown-toggle w-100 h-100" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Category
      </button>
      <div class="dropdown-menu w-100" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="workshops?q[fullname_or_summary_cont]=&q[category_cont]=families&button=">Families</a>
        <a class="dropdown-item" href="workshops?q[fullname_or_summary_cont]=&q[category_cont]=educators&button=">Educators</a>
      </div>
    </div>
    <div class="col-md-7 col-xs-12 my-1"> %>
    <div class="col-xs-12 my-1 d-flex justify-content-between">
      <%= search_form_for @q, :html => {:class => "input-group border rounded-1"} do |f| %>
        <%# <%= f.label "Find a workshop" %>
        <%= f.select :category_cont, ["Families", "Educators"], :prompt => "Category"%>
        <%= f.search_field :fullname_or_summary_cont,:class => "input-lg border-0 flex-grow-1 text-gray", :placeholder => "Find a workshop"  %>
        <%# <%= f.search_field :category_cont,:class => "form-control search input-lg border-0", :placeholder => "Find a workshop"  %>
        <%# <%= f.submit <i class="fa fa-search" title="Search"></i>< %>
        <%= button_tag type: 'submit', class: "btn search btn-default btn-lg" do %>
          <i class="fa fa-search" title="Search"></i>
        <% end %>
      <% end %>

      <%# <form role="search" method="get" action="">
        <div class="input-group border rounded-1">
          <label for="search-courses" class="sr-only">Find a workshop</label>
          <input class="form-control search input-lg" data-list=".list" id="search-courses" name="query" placeholder="Find a workshop" type="text" style="border: none;margin-left: 0.5rem;">
          <span class="input-group-btn">
            <button aria-label="Search Courses" id="search-course-button" class="btn search btn-default btn-lg" type="submit"><i class="fa fa-search" title="Search"></i></button>
          </span>
        </div>
      </form> %>
    </div>
  </div>
</div>


<div class="container py-4">
  <div class="d-flex justify-content-between">
  <%= sort_link(@q, :shortname, 'Sort by Course Name', default_order: :asc, :class=>"text-muted") %>
  <div class="row">
    <% if !user_signed_in? %>
    <% else %>
      <%= link_to 'Your Favorites', {fav: 1}, :class=>"text-muted col-12 col-sm-6 text-center text-nowrap" %>
    <% end %>
    <%= link_to 'Clear Search',workshops_path, :class=>"text-muted col-12 col-sm-6 text-center text-nowrap" %>
  </div>
  </div>
  <div class="row">
    <%# Used to carry params over when adding to cart %>
    <% if !params[:q].nil?
        params[:q].permit!
      end  %>
    <% @workshops.each do |workshop| %>
    <%# <% 8.times do %>
      <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card px-0 m-1 my-3">
            <%= link_to workshop_path(workshop), class: "text-decoration-none" do %>
              <div class="position-relative col-12 col-lg-5" alt="" style="height: 200px; width: 100%; display: block; background-image: url('https://images.unsplash.com/photo-1542330952-bffc55e812b2?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=750&amp;q=80'); background-repeat: no-repeat; background-size: cover; background-position: top center;">
                  <%# <div class="position-absolute top-0 start-0 w-100 h-100 bg-dark d-flex align-items-center justify-content-center " style="opacity: 75%;"></div> %>
              </div>
              <%# <img class="card-img-top" data-src="holder.js/100px200/" alt="100%x200" style="height: 200px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22165%22%20height%3D%22200%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20165%20200%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_182685a30c6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_182685a30c6%22%3E%3Crect%20width%3D%22165%22%20height%3D%22200%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.46666717529297%22%20y%3D%22104.05%22%3E165x200%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true"> %>
              <div class="card-body">
                <%# <h5 class="card-title">Workshop Title</h5> %>
                <h5 class="card-title"><%= workshop.shortname %></h5>
                <p class="card-text">
                  <%= workshop.summary %>
                </p>
                <%# <p class="card-text">This is a summary of the workshop.</p> %>
              <% end %>
              <div class="d-flex justify-content-between align-content-center" >
                <div>
                  <div class="btn btn-primary"> <%= link_to "Enroll Now",  new_user_session_path, :class=>"text-white text-decoration-none" %> </div>
                  <% if @cart.include?(workshop) %>
                    <div class="btn btn-secondary">
                      <%= button_to remove_from_cart_path(workshop), method: :delete, params: {:q=> params[:q], :fav=> params[:fav]} do %>
                        <i class="fa-solid fa-trash-can text-white text-decoration-none"></i>
                      <% end %>
                    </div>
                  <% else %>
                  <div class="btn btn-secondary">
                    <%= button_to add_to_cart_path(workshop), method: :submit, params: {:q=> params[:q], :fav=> params[:fav]}  do %>
                      <i class="fa-solid fa-cart-plus text-white text-decoration-none"></i>
                    <% end %>
                  </div>
                  <% end %>
                </div>
                <turbo-frame id="bookmark_1" class="d-flex align-content-center" >
                  <% if !user_signed_in? %>
                    <div></div>
                  <% elsif current_user.workshops.include?(workshop) %>
                    <% current_bookmark = current_user.bookmarks.find_by workshop:workshop %>
                    <%= button_to bookmark_path(current_bookmark), method: :delete do %>
                      <i class="fa-solid fa-bookmark text-primary" style="font-size: 20px;"></i>
                    <% end %>
                  <% else %>
                    <%= button_to bookmarks_path, method: :post, params: {  :user_id => current_user.id, :workshop_id=> workshop.id } do %>
                      <i class="fa-regular fa-bookmark text-primary" style="font-size: 20px;"></i>
                    <% end %>
                  <% end %>
                </turbo-frame>
              </div>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>