config/routes.rb
Rails.application.routes.draw do
  mount ::Caffeinate::Engine => '/caffeinate'

  get 'cookies/index'
  devise_for :users

  resources :users do
    resources :consultations
    post 'consultations/new', to: 'consultations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#coming_soon'
  root to: 'pages#home'
  # get 'home', to: 'pages#home'
  # get 'families', to: 'pages#family_home'
  get 'educators', to: 'pages#educator_home'
  get 'webinar', to: 'pages#webinar'
  # TODO Update Courses and Change from Workshops
  get 'courses', to: 'workshops#workshops'
  get 'ambassador/family', to: 'pages#ambassador_family'
  get 'ambassador/educators', to: 'pages#ambassador_educator'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact_us'
  get 'consultations', to: 'pages#consultations'
  get 'consultations/purchase', to: 'pages#consultation_purchase'
  get 'GWM', to: 'pages#grow_with_me'
  get 'account', to: 'pages#account'

  get 'cookies', to: 'cookies#index'

  resources :bookmarks, only: [:index, :show, :destroy]
  post 'bookmarks', to: 'bookmarks#create'

  resources :workshops, only: [:show] do
    member do
      get :preview
    end
  end

  get 'workshops', to: 'workshops#workshops'
  post "workshops/add_to_cart/:id", to: "workshops#add_to_cart", as: "add_to_cart"
  post "workshops/add_to_cart_ws_page/:id", to: "workshops#add_to_cart_ws_page", as: "add_to_cart_ws_page"
  delete "workshops/remove_from_cart/:id", to: "workshops#remove_from_cart", as: "remove_from_cart"
  delete 'workshops/remove_from_cart_cart_page/:id', to:'workshops#remove_from_cart_cart_page', as: "remove_from_cart_cart_page"

  get 'create_shopping_cart_order', to: 'orders#create_shopping_cart_order'
  get 'create_consult_order', to: 'orders#create_consult_order'

  resources :orders, only: [:show, :create] do
      resources :payments, only: :new
  end

  get 'cart', to: 'cart#cart'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def cart
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/cart.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col">
      <div class="row text-center">
        <h1>Shopping Cart</h1>
      </div>
      <div class="row py-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-9">
          <table class="table table-hover table-sm">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col">Units</th>
                <th scope="col">Cost per Unit</th>
                <th scope="col">Total</th>
                <th scope="col">Remove</th>
              </tr>
            </thead>
            <tbody>
            <% index = 0 %>
            <% @cart.each do |cart_item| %>
              <% index += 1 %>
              <tr>
                <th scope="row"><%= index %></th>
                <td><%= cart_item.shortname %></td>
                <td>1</td>
                <td><%= humanized_money_with_symbol cart_item.price %> </td>
                <td><strong><%= humanized_money_with_symbol cart_item.price %></strong></td>
                <td>
                  <%= link_to remove_from_cart_cart_page_path(cart_item), method: :delete do %>
                    <i class="fa-solid fa-trash-can text-secondary"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
              <tr>
                <th scope="row"></th>
                <td colspan="2"></td>
                <td><strong>Total Cost of Order</strong></td>
                <%# <td><strong><%= humanized_money_with_symbol @order.amount%></strong></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-lg-2"></div>
      </div>
      <div class="d-flex justify-content-center py-3">
        <%= link_to "Confirm Order & Proceed to Payment",  create_shopping_cart_order_path, :class=>"btn btn-secondary text-white text-decoration-none" %>
      </div>

    </div>
  </div>
</div>