config/routes.rb
Rails.application.routes.draw do
  mount ::Caffeinate::Engine => '/caffeinate'

  get 'cookies/index'
  devise_for :users

  resources :users do
    resources :consultations
    post 'consultations/new', to: 'consultations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#coming_soon'
  root to: 'pages#home'
  # get 'home', to: 'pages#home'
  # get 'families', to: 'pages#family_home'
  get 'educators', to: 'pages#educator_home'
  get 'webinar', to: 'pages#webinar'
  # TODO Update Courses and Change from Workshops
  get 'courses', to: 'workshops#workshops'
  get 'ambassador/family', to: 'pages#ambassador_family'
  get 'ambassador/educators', to: 'pages#ambassador_educator'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact_us'
  get 'consultations', to: 'pages#consultations'
  get 'consultations/purchase', to: 'pages#consultation_purchase'
  get 'GWM', to: 'pages#grow_with_me'
  get 'account', to: 'pages#account'

  get 'cookies', to: 'cookies#index'

  resources :bookmarks, only: [:index, :show, :destroy]
  post 'bookmarks', to: 'bookmarks#create'

  resources :workshops, only: [:show] do
    member do
      get :preview
    end
  end

  get 'workshops', to: 'workshops#workshops'
  post "workshops/add_to_cart/:id", to: "workshops#add_to_cart", as: "add_to_cart"
  post "workshops/add_to_cart_ws_page/:id", to: "workshops#add_to_cart_ws_page", as: "add_to_cart_ws_page"
  delete "workshops/remove_from_cart/:id", to: "workshops#remove_from_cart", as: "remove_from_cart"
  delete 'workshops/remove_from_cart_cart_page/:id', to:'workshops#remove_from_cart_cart_page', as: "remove_from_cart_cart_page"

  get 'create_shopping_cart_order', to: 'orders#create_shopping_cart_order'
  get 'create_consult_order', to: 'orders#create_consult_order'

  resources :orders, only: [:show, :create] do
      resources :payments, only: :new
  end

  get 'cart', to: 'cart#cart'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if purchase_consultations %>
  <div class="row alert alert-warning alert-dismissible fade show m-1 " role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <div class="col-12 col-md-8 mb-1">
    <%= purchase_consultations %>
    </div>
    <div class="col-12 col-md-4 mb-1">
      <%= link_to "Purchase", consultations_purchase_path, class: "btn w-100", style:"/*! outline-color: var(--bs-alert-color); */color: var(--bs-alert-color);border-color: var(--bs-alert-color);" %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="pt-3 border-top">
  <div class="container">
    <div class="row border-bottom">
      <div class="col-12 col-lg-3 mb-10 mb-lg-0">
        <a class="navbar-brand" href="/">
          <%= image_tag "logo_w_bg.png", alt: "Bright Futures Logo", style: "width: 6rem;"%>
        </a>
      </div>
      <div class="col-12 col-lg-9 mb-12">
        <div class="row justify-content-center">
          <div class="col-12 col-sm-6 col-lg-auto mb-8 mb-lg-0">
            <p class="fw-bold mb-6">Products</p>
            <ul class="list-unstyled">
              <%# <li class="mb-3"><%= link_to "Free Webinars",  webinar_path, :class=>"small text-muted text-decoration-none" </li> %>
              <li class="mb-3 small text-muted text-decoration-none">Free Webinars (Coming Soon)</li>
              <li class="mb-3"><%= link_to "Workshops",  workshops_path, :class=>"small text-muted text-decoration-none" %></li>
              <li class="mb-3"><%= link_to "Courses",  courses_path, :class=>"small text-muted text-decoration-none" %></li>
              <li class="mb-3"><%= link_to "Consultations",  consultations_path, :class=>"small text-muted text-decoration-none" %></li>

              <li class="mb-3 small text-muted text-decoration-none">Curriculum &amp; Resources (Coming Soon)</li>
              <li class="small text-muted text-decoration-none">Ambassador Program (Coming Soon)</li>
              <%# <li class="mb-3"><a class="small text-muted text-decoration-none" href="">Curriculum &amp; Resources (Coming Soon)</a></li>
              <li><a class="small text-muted text-decoration-none" href="">Ambassador Program (Coming Soon)</a></li> %>
            </ul>
          </div>

          <div class="col-12 col-sm-6 col-lg-auto mb-8 mb-lg-0">
            <p class="fw-bold mb-6">About</p>
            <ul class="list-unstyled">
              <li class="mb-3"><%= link_to "Mission",  "#{about_path}#mission", :class=>"small text-muted text-decoration-none" %></li>
              <li class="mb-3"><%= link_to "Team",  "#{about_path}#team", :class=>"small text-muted text-decoration-none" %></li>
              <li><%= link_to "Contact Us",  contact_path, :class=>"small text-muted text-decoration-none" %></li>
              <%# <li class="mb-3"><a class="small text-muted text-decoration-none" href="#">Mission</a></li>
              <li class="mb-3"><a class="small text-muted text-decoration-none" href="#">Team</a></li>
              <li><a class="small text-muted text-decoration-none" href="#">Contact Us</a></li> %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="pt-10 text-center">
      <p class="small text-muted" style="padding: .25rem;margin-bottom: 0px;">© Bright Futures Community Consulting LLC I All Rights Reserved</p>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="position-relative navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag "logo_w_bg.png", alt: "Bright Futures Logo", style: "width: 8rem;"%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="d-none d-lg-flex position-absolute top-50 start-50 translate-middle navbar-nav">
      <li class="nav-item nav-link"> <%= link_to "Families", "#{root_path}#fs" %> </li>
      <li class="nav-item nav-link"> <%= link_to "Educators", "#{educators_path}#es" %> </li>
    </ul>
    <div class="d-none d-lg-block">
      <a class="btn me-2 btn-primary text-white text-decoration-none" href="/workshops"> <i class="fa-solid fa-magnifying-glass"></i> Find A Workshop</a>
      <% if user_signed_in? %>
        <div class="btn btn-secondary text-white rounded-circle justify-content-center align-items-center" id="navbarDropdown" data-bs-toggle="dropdown" style= "height: 2.4rem;width: 2.4rem;margin: 0;padding-left: 0px;padding-right: 0px;">
          <%=current_user.first_name[0].capitalize+current_user.last_name[0].capitalize%>
        </div>
        <% if @cart.size >= 1  %>
          <span class="badge badge-notify" style="font-size:10px"><%= @cart.size %></span>
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to(new_user_consultation_path(current_user), :class=>"dropdown-item") do %>
            <p><i class="fa-regular fa-calendar-plus"></i> Book Consultation</p>
          <% end %>
          <%= link_to("https://learning.brightfutures.net", :class=>"dropdown-item") do %>
            <p><i class="fa-solid fa-book-open"></i> Learning Hub</p>
          <% end %>
          <%= link_to(account_path, :class=>"dropdown-item") do %>
            <p><i class="fa-regular fa-circle-user"></i> My Account</p>
          <% end %>
          <%= link_to(destroy_user_session_path, :class=>"dropdown-item", :method=>"Delete") do %>
            <p><i class="fa-solid fa-right-from-bracket"></i> Log out</p>
          <% end %>
          <% if @cart.size >= 1  %>
            <%= link_to(cart_path, :class=>"dropdown-item") do %>
              <p><i class="fa-solid fa-cart-shopping"></i> My Cart</p>
            <% end %>
            <span class="badge badge-notify cart-badge" style="font-size:10px;"><%= @cart.size %></span>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="btn btn-secondary"> <%= link_to "Sign In",  new_user_session_path, :class=>"text-white text-decoration-none" %> </div>
      <% end %>
    </div>
  </div>
</nav>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto d-flex align-items-end p-3">
    <li class="nav-item nav-link"> <%= link_to "Families", "#{root_path}#fs", :class=>"small text-muted text-decoration-none" %> </li>
    <li class="nav-item nav-link"> <%= link_to "Educators", "#{educators_path}#es", :class=>"small text-muted text-decoration-none" %> </li>
    <li class="nav-item nav-link border-top align-self-center"></li>
    <li class="nav-item nav-link">
      <a class="btn btn-primary text-white text-decoration-none" href="/workshops"> <i class="fa-solid fa-magnifying-glass"></i> Find A Workshop</a>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item nav-link">
          <%= link_to(new_user_consultation_path(current_user), :class=>"btn btn-primary text-white text-decoration-none") do %>
            <p style="margin-bottom: 0px;"><i class="fa-regular fa-calendar-plus"></i> Book Consultation</p>
          <% end %>
      <li class="nav-item nav-link">
        <a class="btn btn-primary text-white text-decoration-none" href="https://learning.brightfutures.net"> <i class="fa-solid fa-book-open"></i> Learning Hub</a>
      </li>
      <li class="nav-item nav-link border-top align-self-center"></li>
      <li class="nav-item nav-link">
        <%= link_to(account_path, :class=>"small text-muted text-decoration-none") do %>
          <p><i class="fa-regular fa-circle-user"></i> My Account</p>
        <% end %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to(destroy_user_session_path, :class=>"small text-muted text-decoration-none", :method=>"Delete") do %>
          <p><i class="fa-solid fa-right-from-bracket"></i> Log out</p>
        <% end %>
      </li>
      <li class="nav-item nav-link">
        <% if @cart.size >= 1  %>
          <%= link_to(cart_path, :class=>"small text-muted text-decoration-none") do %>
            <p><i class="fa-solid fa-cart-shopping"></i> My Cart</p>
          <% end %>
          <span class="badge badge-notify cart-badge-mobile" style="font-size:10px;"><%= @cart.size %></span>
        <% end %>
      </li>
    <% else %>
      <li class="nav-item nav-link">
        <div class="btn btn-secondary"> <%= link_to "Sign In",  new_user_session_path, :class=>"text-white text-decoration-none" %> </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/cookies_banner.html.erb
<%= turbo_frame_tag :cookies_modal do %>
  <% if session[:cookies_accepted].nil? # don't re-render if a true/false selected %>
    <section class="cookies-modal">
      <h3>We process cookies.</h3>
      <%= link_to "Accept cookies", cookies_path(cookies: true), method: :post %>
      <%= link_to "Reject cookies", cookies_path(cookies: false), method: :post %>
    </section>
  <% end %>
<% end %>