config/routes.rb
Rails.application.routes.draw do
  mount ::Caffeinate::Engine => '/caffeinate'

  get 'cookies/index'
  devise_for :users

  resources :users do
    resources :consultations
    post 'consultations/new', to: 'consultations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#coming_soon'
  root to: 'pages#home'
  # get 'home', to: 'pages#home'
  # get 'families', to: 'pages#family_home'
  get 'educators', to: 'pages#educator_home'
  get 'webinar', to: 'pages#webinar'
  # TODO Update Courses and Change from Workshops
  get 'courses', to: 'workshops#workshops'
  get 'ambassador/family', to: 'pages#ambassador_family'
  get 'ambassador/educators', to: 'pages#ambassador_educator'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact_us'
  get 'consultations', to: 'pages#consultations'
  get 'consultations/purchase', to: 'pages#consultation_purchase'
  get 'GWM', to: 'pages#grow_with_me'
  get 'account', to: 'pages#account'

  get 'cookies', to: 'cookies#index'

  resources :bookmarks, only: [:index, :show, :destroy]
  post 'bookmarks', to: 'bookmarks#create'

  resources :workshops, only: [:show] do
    member do
      get :preview
    end
  end

  get 'workshops', to: 'workshops#workshops'
  post "workshops/add_to_cart/:id", to: "workshops#add_to_cart", as: "add_to_cart"
  post "workshops/add_to_cart_ws_page/:id", to: "workshops#add_to_cart_ws_page", as: "add_to_cart_ws_page"
  delete "workshops/remove_from_cart/:id", to: "workshops#remove_from_cart", as: "remove_from_cart"
  delete 'workshops/remove_from_cart_cart_page/:id', to:'workshops#remove_from_cart_cart_page', as: "remove_from_cart_cart_page"

  get 'create_shopping_cart_order', to: 'orders#create_shopping_cart_order'
  get 'create_consult_order', to: 'orders#create_consult_order'

  resources :orders, only: [:show, :create] do
      resources :payments, only: :new
  end

  get 'cart', to: 'cart#cart'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/pages/about.html.erb
<section id="mission" class="py-5 poistion-relative overflow-hidden">
  <div class="container">
    <div class="mw-md mw-md-3xl mx-auto">
      <div class="position-relative py-5 py-lg-5 px-5 pe-md-5 mb-5 mb-md-4 bg-warning-light">
        <div class="d-flex">
          <div>
            <p class="lead lh-lg">Bright Futures exists to bring about a global community of empowered caregivers to ensure every child has a bright future.</p>
          </div>
        </div>
      </div>
      <p class="text-muted text-center">Our Mission</p>
    </div>
  </div>
</section>

<section class="spacer border-top border-primary">
</section>

<section id="team" class="py-5">
  <div class="container">
    <div class="mw-3xl mx-auto text-center mb-5">

      <h2 class="mt-5 mb-4">Our Team</h2>

    </div>
    <div class="row">
      <div class="col-12 col-lg-10 mx-auto">
        <div class="row">
          <div class="col-12 mb-5">
            <div class="p-5 bg-light-light">
              <div class="row align-items-center">
                <div class="col-12 col-lg-5 mb-4 mb-lg-0">
                  <%# <img class="img-fluid w-100" style="height: 223px; object-fit: cover;" src="https://images.unsplash.com/photo-1450297350677-623de575f31c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=334&amp;q=80" alt=""> %>
                  <%= image_tag("barbara.jpg",class:"img-fluid w-100", style:"height: 223px; object-fit: cover;", alt: "Barbara Poppell") %>
                </div>
                <div class="col-12 col-lg-7">
                  <h6 class="text-primary mb-2">Barbara Poppell</h6>
                  <p class="mb-2 fw-bold">CEO &amp; Co-Founder</p>
                  <p class="text-muted">Barbara has dedicated her career to helping communities prepare for a better tomorrow through access to information and support. She works to support the healthy development of all children with international communities including families, caregivers and educational institutions.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 mb-5">
            <div class="p-5 bg-light-light">
              <div class="row align-items-center">
                <div class="d-none d-lg-block col-lg-7">
                  <h6 class="text-primary mb-2">Holly Poppell</h6>
                  <p class="mb-2 fw-bold">Co-Founder &amp; Counselor</p>
                  <p class="text-muted">Holly is a parent of children with learning differences. She has nearly 30 years of teaching and counseling experience and earned a Masters degree in Counseling, a post-graduate credential in teaching, and a Bachelor’s degree in Organizational Development.</p>
                </div>
                <div class="col-12 col-lg-5 mb-4 mb-lg-0">
                  <%# <img class="img-fluid w-100" style="height: 223px; object-fit: cover;" src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=750&amp;q=80" alt=""> %>
                </div>
                <div class="col-12 d-lg-none">
                  <h6 class="text-primary mb-2">Holly Poppell</h6>
                  <p class="mb-2 fw-bold">Co-Founder &amp; Counselor</p>
                  <p class="text-muted">Holly is a parent of children with learning differences. She has nearly 30 years of teaching and counseling experience and earned a Masters degree in Counseling, a post-graduate credential in teaching, and a Bachelor’s degree in Organizational Development.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 mb-5">
            <div class="p-5 bg-light-light">
              <div class="row align-items-center">
                <div class="col-12 col-lg-5 mb-4 mb-lg-0">
                  <%# <img class="img-fluid w-100" style="height: 223px; object-fit: cover;" src="app/assets/images/hunter.jpg" alt="Hunter Bourgeois"> %>
                  <%= image_tag("hunter.jpg",class:"img-fluid w-100", style:"height: 223px; object-fit: cover;", alt: "Hunter Bourgeois") %>
                </div>
                <div class="col-12 col-lg-7">
                  <h6 class="text-primary mb-2">Hunter Bourgeois</h6>
                  <p class="mb-2 fw-bold">COO</p>
                  <p class="text-muted">Hunter is an international entrepreneur with extensive experience across countries, cultures and  companies. He consistently leads cross-functional teams to launch new products on-time and at the highest quality.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 mb-5">
            <div class="p-5 bg-light-light">
              <div class="row align-items-center">
                <div class="d-none d-lg-block col-lg-7">
                  <h6 class="text-primary mb-2">Natalie Brimacombe</h6>
                  <p class="mb-2 fw-bold">Head of Curriculum</p>
                  <p class="text-muted">Natalie is an international early years teacher with a passion for developmentally appropriate practices. She has worked for over ten years across Asia and the Middle East delivering high quality, early education in large international schools and early childhood centres.</p>
                </div>
                <div class="col-12 col-lg-5 mb-4 mb-lg-0">
                  <%# <img class="img-fluid w-100" style="height: 223px; object-fit: cover;" src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=750&amp;q=80" alt=""> %>
                </div>
                <div class="col-12 d-lg-none">
                  <h6 class="text-primary mb-2">Natalie Brimacombe</h6>
                  <p class="mb-2 fw-bold">Head of Curriculum</p>
                  <p class="text-muted">Natalie is an international early years teacher with a passion for developmentally appropriate practices. She has worked for over ten years across Asia and the Middle East delivering high quality, early education in large international schools and early childhood centres.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/ambassador_educator.html.erb
<h1>Ambassador Program - Educators</h1>

app/views/pages/consultation_purchase.html.erb
<section class="py-5">
  <div class="container">
    <div class="row d-flex align-items-center mb-5">
      <div class="vh-70 col-12 col-lg-6">
        <h2 style="margin-bottom: 1rem;">Purchase Consultations</h2>
      </div>
      <div class="col-12 col-lg-6">
        <div class="mw-lg-md ms-lg-auto">
          <p class="lead lh-lg text-muted">Sometimes we all need a bit more help. Whether you are a parent or a teacher, let our experts spend some one-on-one time together with you.</p>
        </div>
      </div>
    </div>
    <div class="row align-items-center p-5 p-lg-12 bg-light mb-5">
      <div class="col-12 col-lg-5 mb-4">
        <h3 class="mb-4 text-center">Single Session</h3>
      </div>
      <div class="col-12 col-lg-2 mb-4 mb-lg-0">
      </div>
      <div class="col-12 col-lg-3 mb-4 text-center">
        <h2 class="text-primary">$149.99</h2>
        <p class="mb-0 text-muted">per session</p>
      </div>
      <div class="col-12 col-lg-2 mb-4">
        <%= link_to "Purchase now", create_consult_order_path(quantity: 1), class: "btn btn-primary w-100" %>
      </div>
    </div>
    <div class="row align-items-center p-5 p-lg-12 mb-5 bg-primary">
      <div class="col-12 col-lg-5 mb-4">
        <h3 class="text-white mb-4 text-center">Five Sessions</h3>
      </div>
      <div class="col-12 col-lg-2 mb-4 mb-lg-0">
      </div>
      <div class="col-12 col-lg-3 mb-4 text-center">
        <h2 class="text-white">$119.99</h2>
        <p class="mb-0 text-white">per session</p>
      </div>
      <div class="col-12 col-lg-2 mb-4">
        <%= link_to "Purchase now", create_consult_order_path(quantity: 5), class: "btn btn-secondary w-100" %>
      </div>
    </div>
  </div>
</section>
<section class="spacer border-top border-primary">
</section>
  <section class="py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6 mb-8 mb-lg-0">
          <div class="mw-lg-md">
            <h3 class="my-5">Looking For&nbsp;
              School-wide Solutions?</h3>
            <p class="lead lh-lg text-muted mb-5">Bright Futures has experience guiding different international schools and school systems. We're here to help.</p>
            <a class="btn btn-primary" href="/contact">Get in Touch</a>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="p-5 bg-light-light">
            <div class="d-flex mb-5">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">1</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Professional Development Courses</h6>
              </div>
            </div>
            <div class="d-flex mb-5">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">2</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Custom Workshops</h6>
              </div>
            </div>
            <div class="d-flex">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">3</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Technical Assistance</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/pages/consultations.html.erb
<section class="py-5">
  <div class="container">
    <div class="row d-flex align-items-center mb-5">
      <div class="vh-70 col-12 col-lg-6">
        <h2 style="margin-bottom: 1rem;">Book A Consultation</h2>
      </div>
      <div class="col-12 col-lg-6">
        <div class="mw-lg-md ms-lg-auto">
          <p class="lead lh-lg text-muted">Sometimes we all need a bit more help. Whether you are a parent or a teacher, let our experts spend some one-on-one time together with you.</p>
        </div>
      </div>
    </div>
    <div class="row align-items-center p-5 p-lg-12 bg-light mb-5">
      <div class="col-12 col-lg-5 mb-4">
        <h3 class="mb-4 text-center">Book a Single Session</h3>
      </div>
      <div class="col-12 col-lg-2 mb-4 mb-lg-0">
      </div>
      <div class="col-12 col-lg-3 mb-4 text-center">
        <%# <h2 class="text-primary">$49.99</h2>
        <p class="mb-0 text-muted">per session</p> %>
      </div>
      <div class="col-12 col-lg-2 mb-4">
        <% if user_signed_in? %>
          <%= link_to "Book now", new_user_consultation_path(current_user), class: "btn btn-primary w-100" %>
        <% else %>
          <%= link_to "Book now", new_user_session_path, class: "btn btn-primary w-100" %>
        <% end %>
      </div>
    </div>
    <div class="row align-items-center p-5 p-lg-12 mb-5 bg-primary">
      <div class="col-12 col-lg-5 mb-4">
        <h3 class="text-white mb-4 text-center">Purchase A Consultation Package</h3>
      </div>
      <div class="col-12 col-lg-2 mb-4 mb-lg-0">
      </div>
      <div class="col-12 col-lg-3 mb-4 text-center">
        <h2 class="text-white">From $39.99</h2>
        <p class="mb-0 text-white">per session</p>
      </div>
      <div class="col-12 col-lg-2 mb-4">
        <%= link_to "Purchase", consultations_purchase_path, class: "btn btn-secondary w-100" %>
      </div>
    </div>
  </div>
</section>
<section class="spacer border-top border-primary">
</section>
  <section class="py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6 mb-8 mb-lg-0">
          <div class="mw-lg-md">
            <h3 class="my-5">Looking For&nbsp;
              School-wide Solutions?</h3>
            <p class="lead lh-lg text-muted mb-5">Bright Futures has experience guiding different international schools and school systems. We're here to help.</p>
            <a class="btn btn-primary" href="/contact">Get in Touch</a>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="p-5 bg-light-light">
            <div class="d-flex mb-5">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">1</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Professional Development Courses</h6>
              </div>
            </div>
            <div class="d-flex mb-5">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">2</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Custom Workshops</h6>
              </div>
            </div>
            <div class="d-flex">
              <span class="flex-shrink-0 d-flex align-items-center justify-content-center bg-secondary me-5 text-white" style="width: 64px; height: 64px;">3</span>
              <div class="d-flex align-items-center">
                <h6 class="mb-0">Technical Assistance</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/pages/home.html.erb
<section class="position-relative py-48" style="height: 90vh; background-image: linear-gradient(to bottom,rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.6)), url('https://images.unsplash.com/photo-1534224563519-fea04849cadf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80'); background-repeat: no-repeat; background-size: cover; background-position: center;">
  <%# <div class="position-absolute top-0 start-0 w-100 h-100 bg-dark" style="opacity: 75%;"></div> %>
  <div class="position-relative container h-100 text-center d-flex align-items-center justify-content-center">
    <h2 class="mt-4 mb-3 text-white">Supporting the International Community for a Brighter Tomorrow</h2>
  </div>
</section>

<section id="fs" class="py-5 bg-primary">
  <div class="container">
    <div class="mw-4xl mx-auto text-center">
      <h2 class="mt-6 mb-4 text-white">Understand More About Your Child</h2>
      <p class="mb-6 mw-2xl mx-auto lead text-light">If you have ever wondered how to develop your brand, this is the place for you. Take a big step forward in growing your business with this great tool.</p>
      <a class="btn btn-secondary d-block d-md-inline-block mb-2 mb-md-0 me-md-4" href="/workshops?q[category_cont]=families&q[fullname_or_summary_cont]=&button=">See Our Workshops</a>
    </div>
  </div>
</section>
<section class="py-20" style="padding: 4rem;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 col-lg-7 mb-10 mb-lg-0">
        <div class="mw-lg-md position-relative">
          <img class="img-fluid h-100" style="object-fit: cover; padding: 1rem;" src="https://images.unsplash.com/photo-1605812830455-2fadc55bc4ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="">
        </div>
      </div>
      <div class="col-12 col-lg-5">
        <div class="mw-lg-md mx-auto">
          <h3 class="mb-14">The Benefits of Developmentally Appropriate Practice</h3>
          <div class="mt-3 d-flex align-items-start mb-6">
            <span class="me-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                <path d="M8 11.5L11 14.5L17 8.5" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
              </svg>
            </span>
            <div>
              <h5>Start having fun, hands-on activities that are proven to help your child learn</h5>
              <%# <p class="lh-lg text-muted mb-0">Take care to develop resources continually and integrity them with previous projects.</p> %>
            </div>
          </div>
          <div class="mt-3 d-flex align-items-start mb-6">
            <span class="me-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                <path d="M8 11.5L11 14.5L17 8.5" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
              </svg>
            </span>
            <div>
              <h5>Help your child quickly develop new knowledge and practical skills</h5>
              <%# <p class="lh-lg text-muted mb-0">Take care to develop resources continually and integrity them with previous projects.</p> %>
            </div>
          </div>
          <div class="mt-3 d-flex align-items-start">
            <span class="me-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                <path d="M8 11.5L11 14.5L17 8.5" stroke="#006251" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
              </svg>
            </span>
            <div>
              <h5>Allow your child to have an active role in their learning and development</h5>
              <%# <p class="lh-lg text-muted mb-0">Take care to develop resources continually and integrity them with previous projects.</p> %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="spacer border-top border-primary">
</section>
<section class="py-5">
  <div class="container">
    <div class="mw-xl text-center mx-auto mb-12">
      <h2 class="my-5">Raising Children Is Difficult. We Can Help:</h2>
    </div>
    <div class="row align-items-center">
      <div class="col-12 col-lg-4 mb-5 mb-lg-0">
        <div class="mw-xl mx-auto p-5 text-center secondary-product-box">
          <h2 class="text-primary mb-5">Courses</h2>
          <a class="btn btn-primary w-100" href="/courses">Start Now</a>
        </div>
      </div>
      <div class="col-12 col-lg-4 mb-5 mb-lg-0">
        <div class="mw-xl mx-auto p-5 bg-primary text-center">
          <h2 class="text-white mb-5">Workshops</h2>
          <a class="btn btn-light w-100" href="/workshops?q[category_cont]=families&q[fullname_or_summary_cont]=&button=">Start Now</a>
        </div>
      </div>
      <div class="col-12 col-lg-4">
        <div class="mw-xl mx-auto p-5 text-center secondary-product-box">
          <h2 class="text-primary mb-5">Consultations</h2>
          <%= link_to "Book Now", consultations_path, class: "btn btn-primary w-100" %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="spacer border-top border-primary">

<%# Testimonials, Hidden %>
<%# <section class="py-5">
  <div class="container">
    <div class="mw-xl mx-auto text-center mb-6">

      <h2 class="mt-6">Happy Kids = Happy Parents!


        Here's the Proof</h2>
    </div>
    <div class="row align-items-center justify-content-center">
      <button class="d-none d-lg-inline-flex btn btn-primary align-items-center justify-content-center p-0" style="width: 64px; height: 64px">
        <svg style="width: 24px; height: 24px;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M8.70711 12H18.5C18.7761 12 19 12.2239 19 12.5C19 12.7761 18.7761 13 18.5 13H8.70711L11.8536 16.1464C12.0488 16.3417 12.0488 16.6583 11.8536 16.8536C11.6583 17.0488 11.3417 17.0488 11.1464 16.8536L7.14645 12.8536C6.95118 12.6583 6.95118 12.3417 7.14645 12.1464L11.1464 8.14645C11.3417 7.95118 11.6583 7.95118 11.8536 8.14645C12.0488 8.34171 12.0488 8.65829 11.8536 8.85355L8.70711 12Z" fill="white"></path>
        </svg>
      </button>
      <div class="col-12 col-lg-10 px-lg-0 text-center">
        <div class="p-5 px-lg-20 py-lg-12 bg-light-light text-center mb-6">
          <p class="lead lh-lg text-muted mb-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dignissim quam ultricies, placerat tellus sed, laoreet orci. Duis luctus quam ac metus gravida sodales. Sed a ex accumsan, pellentesque sem eget, scelerisque dolor.</p>
          <img class="mx-auto img-fluid mb-4 rounded-circle" style="width: 88px; height: 88px; object-fit: cover; object-position: right;" src="https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=750&amp;q=80" alt="">
          <h6 class="text-primary">Danny Bailey</h6>
          <p class="fw-bold">CEO &amp; Founder</p>
        </div>
        <div class="text-center">
          <button class="btn btn-light p-0 me-2" style="width: 12px; height: 12px; transform: rotate(45deg);"></button>
          <button class="btn btn-light p-0 me-2" style="width: 12px; height: 12px; transform: rotate(45deg);"></button>
          <button class="btn btn-primary p-0 me-2" style="width: 12px; height: 12px; transform: rotate(45deg);"></button>
          <button class="btn btn-secondary p-0" style="width: 12px; height: 12px; transform: rotate(45deg);"></button>
        </div>
      </div>
      <button class="d-none d-lg-inline-flex btn btn-primary align-items-center justify-content-center p-0" style="width: 64px; height: 64px">
        <svg style="width: 24px; height: 24px;" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M17.2929 13H7.5C7.22386 13 7 12.7761 7 12.5C7 12.2239 7.22386 12 7.5 12H17.2929L14.1464 8.85355C13.9512 8.65829 13.9512 8.34171 14.1464 8.14645C14.3417 7.95118 14.6583 7.95118 14.8536 8.14645L18.8536 12.1464C19.0488 12.3417 19.0488 12.6583 18.8536 12.8536L14.8536 16.8536C14.6583 17.0488 14.3417 17.0488 14.1464 16.8536C13.9512 16.6583 13.9512 16.3417 14.1464 16.1464L17.2929 13Z" fill="white"></path>
        </svg>
      </button>
    </div>
  </div>
</section> %>
<section class="spacer border-top border-primary">
</section>
<section class="py-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 col-lg-6 mb-10 mb-lg-0">
        <div class="mw-lg-sm mx-auto">
          <h2 class="mb-6">Learn More With Our Free Webinars</h2>
          <p class="lead lh-lg text-muted mb-6">As a parent, you want to do what's right for your children. Checkout our Free Webinars to see if our courses are right for your family.</p>
          <div class="btn btn-primary d-block d-md-inline-block mb-6 mb-md-0 mb-lg-0 me-md-4">
            <%= link_to "Coming Soon", "#{webinar_path}#families", :class=>"text-white text-decoration-none", :style => "pointer-events: none;" %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6 position-relative">
        <div class="d-flex flex-column mx-auto" style="width: 296px;">
          <div class="d-flex justify-content-end align-items-end">
            <img class="ms-auto img-fluid" style="width: 296px; height: 296px; object-fit: cover;" src="https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=890&amp;q=80" alt="">
          </div>
          <div class="d-flex justify-content-end">
            <img class="img-fluid" style="height: 148px; width: 148px; object-fit: cover;" src="https://images.unsplash.com/photo-1600275669439-14e40452d20b?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=334&amp;q=80" alt="">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="py-5 bg-primary">
  <div class="container">
    <div class="mw-4xl mx-auto text-center">
      <h2 class="mt-3 text-white">Book A One-On-One Consultation</h2>
      <p class="mb-6 mw-2xl mx-auto lead text-light">Need a bit more help? We got you.</p>
      <a class="btn btn-secondary d-block d-md-inline-block mb-2 mb-md-0 me-md-4" href="/consultations">Schedule Now</a>
    </div>
  </div>
</section>